[package]
name = "frob"
version = "0.1.0"
authors = ["Anton Rechenauer <antonrechenauer@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
dotenv = "0.15.0"
primal = "0.3.1"
clap = {version = "4.0.26", features = ["derive"] }
crossbeam = "0.8.2"
ndarray = "0.15.6"
petgraph = "0.6.2"